# Site
repository: Mofan-coding/Mofan-coding.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Mofan Zhang
title: a nature lover & student at Hogwarts
email: mzhang90@jhu.edu
phone: 443-934-8881


# Dark Mode (true/false/never)
darkmode: false

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: https://i.ibb.co/tLMJM4H/Hogwarts-Mofan.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, welcome to my page! My name is Mofan Zhang, a graduate student and research assitant at Johns Hopkins University. I love learning coding and mathematics(Optimization and Statistics), also immersing myself in nature. I'm much interested in decision making under uncertainty in complex system. 

  Please check my **full CV** here for more detailed information of research experiences:

    - <a href="https://drive.google.com/file/d/1nywywGKbijh3y28xZi5wgIro8WOZO3Oi/view?usp=sharing">CV</a>

# Education Section
# education_title: Education #(Use this to override about education section title) 

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  In my spare time, I enjoy playing the piano and listening to classic music (big fan of Claude Debussy).<br/>
  I also love reading books, here are two of my favorite ones:<br/> 
  Harry Potter by J. K. Rowling, has been with me since I was a little girl, taught me to be brave and kind, always strive for excellence (from Hermione Granger).<br/>
  The Alchemist by Paulo Coelho, inspired me to live in the moment and make everyday count.<br/>
  I worked as president of student association for small animall protection in undergraduate school and led a team of volunteers to rescue animals in and out campus, also provided food and shelter to animals living in campus.<br/>
  ![Image of cats](https://i.ibb.co/ysD2rHX/cat-shelter.jpg)
  ![Image of cats1](https://i.ibb.co/McHVtfJ/cat.jpg)



# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
